### ISSUE TITLE
Is it necessary for environment name in database.yml?

### ISSUE THREAD

**Issue by kouyaf77** [eagletmt/switch_point#16]
I encountered this exception `ActiveRecord::AdapterNotSpecified: 'development' database is not configured. Available: ["default", "development_master", "development_slave"]` If I configure like the following.

In database.yml:
```yml
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: testapp
  password: testapp
  database: testapp_development

development_master:
  <<: *default
  host: 127.0.0.1

development_slave:
  <<: *default
  host: 192.168.50.2
```
In initializer:
```rb
 SwitchPoint.configure do |config|
   config.define_switch_point :db1,
     readonly: :"#{Rails.env}_slave",
     writable: :"#{Rails.env}_master"
 end
```

That's fine If I configure like the following.
In database.yml:
```yml
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: testapp
  password: testapp
  database: testapp_development

development:
  <<: *default
  host: 127.0.0.1

development_slave:
  <<: *default
  host: 192.168.50.2
```
In initializer:
```rb
 SwitchPoint.configure do |config|
   config.define_switch_point :db1,
     readonly: :"#{Rails.env}_slave",
     writable: :"#{Rails.env}"
 end
```

So is it necessary for environment name(like development, production and test) in database.yml?
